name: Build XML Representation
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:


permissions:
  contents: read
  packages: write

jobs:
  XML:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'XML Representation'
      sonarProjectName: 'GuicedEE_XMLRepresentation'
      sonarOrganization: 'guicedee'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit
